[package]
name = "spacetrace-dupes"
description = "Finding files with identical contents, cheaply"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
spacetrace-scan-core.workspace = true
blake3.workspace = true
rayon.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile = "3"
